# Generated by Django 4.2.4 on 2025-04-17 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
