# Generated by Django 5.1.7 on 2025-04-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('charging', 'Charging'), ('full_charged', 'Full Charged')], default='full_charged', max_length=20),
        ),
    ]
