# Generated by Django 5.1.7 on 2025-04-11 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d474b1f-4a93-4eac-8cc7-842c440d50bd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
