# Generated by Django 4.2.4 on 2025-04-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_store_product_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='barcode',
            new_name='product_id',
        ),
    ]
