# Generated by Django 4.2.4 on 2025-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
